baseURL = 'https://doc.bomnipotent.wwh-soft.com/'
languageCode = 'en-us'
title = 'BOMnipotent'
theme = 'relearn'

[frontmatter]
lastmod = ["lastmod", ":fileModTime"]

[taxonomies]
  tag = "tags"

[outputs]
  # activate the feature to print whole chapters
  home = ['html', 'rss', 'print']
  section = ['html', 'rss', 'print']
  page = ['html', 'rss', 'print']

[params]
themeVariantAuto = ['wwh-light', 'wwh-dark']
collapsibleMenu = true # Display icon next to expandable menu items

[[params.themeVariant]]
identifier = 'auto'

[[params.themeVariant]]
identifier = 'wwh-light'
name = 'Light'

[[params.themeVariant]]
identifier = 'wwh-dark'
name = 'Dark'

defaultContentLanguage = 'en'

[languages]
  [languages.en]
    languageCode = 'en'
    languageName = 'English'
    weight = 1 # Default language needs to be the first in the list

  [languages.de]
    languageCode = 'de'
    languageName = 'Deutsch'

# Render HTML code in Markdown.
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
