baseURL = 'https://doc.bomnipotent.wwh-soft.com/'
languageCode = 'en-us'
title = 'BOMnipotent'
theme = 'relearn'
copyright = "© {currentYear} Weichwerke Heidrich Software"
enableRobotsTXT = true

[frontmatter]
lastmod = ["lastmod", ":fileModTime"]

[taxonomies]
  tag = "tags"

[params]
themeVariantAuto = ['wwh-light', 'wwh-dark']
collapsibleMenu = true # Display icon next to expandable menu items
alwaysopen = false
author.name = 'Weichwerke Heidrich Software'
author.emailname = 'info@wwh-soft.com'
titleSeparator = '|'

[[params.themeVariant]]
identifier = 'auto'

[[params.themeVariant]]
identifier = 'wwh-light'
name = 'Light'

[[params.themeVariant]]
identifier = 'wwh-dark'
name = 'Dark'

defaultContentLanguage = 'en'

[languages]
  [languages.en]
    languageCode = 'en'
    languageName = 'English'
    weight = 1 # Default language needs to be the first in the list

  [languages.de]
    languageCode = 'de'
    languageName = 'Deutsch'

[outputs]
  # activate the feature to print whole chapters
  home = ['html', 'rss', 'print']
  section = ['html', 'rss', 'print']
  page = ['html', 'rss', 'print']

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

# Render HTML code in Markdown.
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
