baseURL = 'https://doc.bomnipotent.de/'
languageCode = 'en-us'
title = 'BOMnipotent'
theme = 'relearn'
copyright = "© {currentYear} Weichwerke Heidrich Software"
enableRobotsTXT = true

[frontmatter]
lastmod = ["lastmod", ":fileModTime"]
date = ["date", "lastmod", ":fileModTime"]

[taxonomies]
  tag = "tags"

[params]
themeVariantAuto = ['wwh-light', 'wwh-dark']
collapsibleMenu = true # Display icon next to expandable menu items
alwaysopen = false
author.name = 'Weichwerke Heidrich Software'
author.emailname = 'info@wwh-soft.com'
titleSeparator = '|'

[[params.themeVariant]]
identifier = 'auto'

[[params.themeVariant]]
identifier = 'wwh-light'
name = 'Light'

[[params.themeVariant]]
identifier = 'wwh-dark'
name = 'Dark'

defaultContentLanguage = 'en'

[languages]
  [languages.en]
    languageCode = 'en'
    languageName = 'English'
    weight = 1 # Default language needs to be the first in the list

  [languages.de]
    languageCode = 'de'
    languageName = 'Deutsch'

[[languages.en.menu.shortcuts]]
  pre = '<i class="fa-solid fa-download"></i> '
  name = 'Download BOMnipotent'
  url = 'https://www.bomnipotent.de/downloads/'
  weight = 100
[[languages.en.menu.shortcuts]]
  pre = '<i class="fab fa-docker"></i> '
  name = 'Get the container'
  url = 'https://hub.docker.com/u/wwhsoft'
  weight = 101
[[languages.en.menu.shortcuts]]
  pre = '<i class="fa-brands fa-github"></i> '
  name = 'Report an issue'
  url = 'https://github.com/Weichwerke-Heidrich-Software/bomnipotent_doc/issues'
  weight = 102
[[languages.en.menu.shortcuts]]
  pre = '<i class="fa-brands fa-linkedin"></i> '
  name = 'Read Marketing'
  url = 'https://www.linkedin.com/company/weichwerke-heidrich-software'
  weight = 103


[[languages.de.menu.shortcuts]]
  pre = '<i class="fa-solid fa-download"></i> '
  name = 'BOMnipotent Herunterladen'
  url = 'https://www.bomnipotent.de/de/downloads/'
  weight = 100
[[languages.de.menu.shortcuts]]
  pre = '<i class="fab fa-docker"></i> '
  name = 'Container nutzen'
  url = 'https://hub.docker.com/u/wwhsoft'
  weight = 101
[[languages.de.menu.shortcuts]]
  pre = '<i class="fa-brands fa-github"></i> '
  name = 'Problem melden'
  url = 'https://github.com/Weichwerke-Heidrich-Software/bomnipotent_doc/issues'
  weight = 102
[[languages.de.menu.shortcuts]]
  pre = '<i class="fa-brands fa-linkedin"></i> '
  name = 'Marketing lesen'
  url = 'https://www.linkedin.com/company/weichwerke-heidrich-software'
  weight = 103

[outputs]
  # activate the feature to print whole chapters
  home = ['html', 'rss', 'print']
  section = ['html', 'rss', 'print']
  page = ['html', 'rss', 'print']

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

# Render HTML code in Markdown.
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
